### ISSUE TITLE
What is the difference between '"(())"', '(())' and (())?

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry-incubator/fissile#345]
In role-manifest.yml, the "templates" part contains some properties, there are several formats:
templates:
    one: '"((ONE))"'
    two: '((TWO))'
    three: ((THREE))

What is the difference between '"(())"', '(())' and (())?

**Comment by mook-as** [comment]
There is no actual difference; they all get parsed as YAML. But format one (two levels of quoting) may be required, if the expanded value is a string that looks like a number and it needs to go through multiple levels of YAML parsing (there's one in configgin as well).

The pass where fissile parses it to put it into `/opt/fissile/env2conf.yml` (in the docker images) should round trip fine, and that file gets parsed by configgin.

Let me know if that explanation is too confusing… because it sort of is :D

**Comment by qibobo** [comment]
@mook-as  For format one: "But format one (two levels of quoting) may be required, if the expanded value is a string that looks like a number and it needs to go through multiple levels of YAML parsing (there's one in configgin as well)." Could you give an example?

**Comment by mook-as** [comment]
Looking more at this, I _think_ that might actually be obsolete (sort of).

- Fissile copies it, verbatim, to `env2conf.yml` in the docker images
- Configgin loads it in [here](https://github.com/SUSE/configgin/blob/fb0c794c166369763943714bf273a8cbeb5ed125/bin/configgin#L19)
- [`#transmogrify`](https://github.com/SUSE/configgin/blob/fb0c794c166369763943714bf273a8cbeb5ed125/lib/environment_config_transmogrifier.rb#L41) then (repeatedly) applies mustache templating to it
- Which happens in [`#processMustacheTemplate`](https://github.com/SUSE/configgin/blob/fb0c794c166369763943714bf273a8cbeb5ed125/lib/environment_config_transmogrifier.rb#L62). (This will always strip one level of quoting)

So it should only end up needing multiple levels if it goes through multiple expansions (now), I think. I believe that previously fissile would do one level of unquoting as well, but we fixed it at some point?  Looks like it was initially added in https://github.com/SUSE/scf/commit/1aeb76d4c772e3450da76ec2a4a810a74e9efdfb but the [relevant PR](https://github.com/SUSE/scf/pull/183) didn't mention it.

(In general, I've been reducing the level of quoting when I touch things, but others might not have been…)

**Comment by jandubois** [comment]
This was not an issue, but a question, and seems to have been answered.
