### ISSUE TITLE
Support for BOSH deployment manifests in configgin

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/fissile#371]
- [ ] Change configgin so it accepts input from a BOSH deployment manifest
- [ ] Change fissile so it generates pods that mount a deployment manifest secret
- [ ] Add `--deployment-manifest-template` to `fissile build helm`

Full spec for this feature lives [here](https://github.com/SUSE/fissile/wiki/Support-for-BOSH-deployment-manifests-V2).

**Comment by bkrannich** [comment]
I wonder what a thought experiment around "what would happen if instead of configgin taking a BOSH deployment manifest we would try and remove configgin from the equation?" would yield.

**Comment by viovanov** [comment]
@bkrannich we just need "something" to render erb templates.
Right now configgin wraps the [`bosh-template`](https://rubygems.org/gems/bosh-template/versions/2.0.0) gem and adds a bit of code to be kube aware and environment aware.

In the end, configgin will be a very thin wrapper for the gem, just so you can call it from the CLI, and it won't exist in each deployment container. It will be used by the operator directly. 

Going through the thought experiment:

- remove configgin
- what do we use for rendering ERB templates?
- we _need_ something ruby - no way around that
- we should use the `bosh-template` gem so we get results consistent with the bosh agent
- how do we call the `bosh-template` gem? our process is go
- we need to wrap it (with a CLI or some API)
- I think CLI is simpler and would work well as a Kube job

**Comment by bkrannich** [comment]
@viovanov - that's for cases where there's actually ERB as part of the manifest, I guess. What about cases where there isn't (or are those too rare to consider)?
