### ISSUE TITLE
Implement the no-monit tag

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry-incubator/fissile#373]
- [ ] Spike to find what information we need to be able to remove monit?
- [ ] Spike to see how we can use [BPM](https://github.com/cloudfoundry-incubator/bpm-release/blob/master/README.md) to get the information needed at 1)
- [ ] Use knowledge from 1) and 2) generate helm charts with an alternative entrypoint
- [ ] Add no-monit for metron in SCF

**Comment by bkrannich** [comment]
I believe ultimately the work done over in https://github.com/cloudfoundry-incubator/bpm-release/blob/master/README.md should factor in here. I believe one of the goals of BPM was also to remove the dependency to monit, eventually.
