### ISSUE TITLE
Race condition for active/passive pods when no leader is available

### ISSUE THREAD

**Issue by qu1queee** [cloudfoundry-incubator/fissile#466]
For HA pods like the `diego-api` with active/passive roles, there is a race condition that will not allow the `skiff-role-active` label to be set to its correct state(true/false).

For the specific use case(diego-api pod), this can happen when the `readines-probe.sh` its executed  when the `bbs` job in the leader pod stops working(not marked as `running`), which will block the `readiness-probe.sh` on reaching the script [part](https://github.com/cloudfoundry-incubator/fissile/blob/develop/scripts/dockerfiles/readiness-probe.sh#L34-L60) where the label can be set to `false`.

An example of such situation is when a connection to the db is lost, which will leave one `diego-api` pod marked as `skiff-role-active` = `true`, when that value is not true.

This is not critical, but I considered important to highlight.

**Comment by mook-as** [comment]
So we basically need to update that script to call `update_readiness false` unless it actually passes a readiness probe (or there isn't one, in which case it get unset)…

**Comment by qu1queee** [comment]
I´not sure how reliable is the readiness probe, while the checks [here](https://github.com/cloudfoundry-incubator/fissile/blob/develop/scripts/dockerfiles/readiness-probe.sh#L30-L32) could be successful even if the job is down. For example, if the `bbs` job for `diego-api` is down, the additional readiness will execute the `head -c0 </dev/tcp/${HOSTNAME}/8891`(see [line](https://github.com/SUSE/scf/blob/develop/container-host-files/etc/scf/config/role-manifest.yml#L449)),  returning an exit code `0`.(pls correct me if im wrong). I would probably move [this block](https://github.com/cloudfoundry-incubator/fissile/blob/develop/scripts/dockerfiles/readiness-probe.sh#L34-L60)  before monit checks, so it will ensure the label of `skiff-role-active` can be set to false, opinions?

**Comment by mook-as** [comment]
I was thinking of something like
- Set trap to set active to false on exit
- Current stuff
- Erase trap, set active to true
Basically, try to ensure that we set the active flag however we exit, instead of just on the happy path. After all, the script (with `errexit`) is designed to abort early on failure, anyway.

Would that cover everything (and be less likely to be broken as we change the script)?

**Comment by qu1queee** [comment]
yes, sorry for the late response(I already saw the merged PR). Trapping that method on EXIT was a nice idea.
